#	$NetBSD$

.include <bsd.init.mk>

.PATH: ${DIST}/samples/hook/child-down.d

FILES=01setkey 01setkey-fix 02ifconfig-gif 03arp
FILESDIR=/usr/share/examples/racoon2/hook/child-down.d

.include <bsd.files.mk>
