#	$NetBSD$

.include <bsd.init.mk>

.PATH: ${DIST}/samples/rc.d

FILES= iked kinkd racoon2 spmd 
FILESBUILD=yes

FILESDIR=/usr/share/examples/racoon2/rc.d

CLEANFILES+= ${FILES}

.include <bsd.files.mk>
