#	$NetBSD$

.include <bsd.init.mk>

.PATH: ${DIST}/samples/hook/child-up.d

FILES=00childup_sample 01setkey 02ifconfig-gif 03arp
FILESDIR=/usr/share/examples/racoon2/hook/child-up.d

.include <bsd.files.mk>
